site_name: HPC101-Labs-2023
theme:
  name: material
  logo: assets/zjusct.png
  favicon: assets/zjusct.png
nav:
  - Lab1-简单集群搭建: Lab1-MiniCluster/index.md
  - Lab2-向量化计算: Lab2-Vectors/index.md
  - Lab2.5-Bonus 手写 SIMD 向量化: Lab2.5-Vectors-Bonus/index.md
  - Lab3-CUDA 使用基础: Lab3-Cuda/index.md
  - Lab4-PCG Solver: Lab4-PCG-Solver/index.md
  - Lab5-简单神经网络训练与加速: Lab5-DL/index.md
  - Project-并行优化: Project-Pivot/index.md
markdown_extensions:
  - admonition #MkDocs 警告框
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
